### ISSUE TITLE
Ruby 2.5

### ISSUE THREAD

**Issue by erkie** [iZettle/api-model#7]
Has this been tested with Ruby 2.5?

**Comment by janneh** [comment]
Might need to bump the version of some dependencies but else I think it should be 🙆‍♂️K

👋

**Comment by erkie** [comment]
👋 👋 👋 👋 👋 👋 👋

**Comment by janneh** [comment]
Closed by https://github.com/iZettle/api-model/pull/8/files

**Comment by erkie** [comment]
THANKS JANNE! WOOOOOOOOOOOOOOOOOO FINALLY

**Comment by erkie** [comment]
![zc0rvcj](https://user-images.githubusercontent.com/21059/38725067-71a21548-3f06-11e8-8d0e-f80dde1a0743.gif)
